# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/slow/sfSnakePro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/slow/sfSnakePro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slow/sfSnakePro/CMakeFiles /home/slow/sfSnakePro//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slow/sfSnakePro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/element/Button.o: src/element/Button.cpp.o
.PHONY : src/element/Button.o

# target to build an object file
src/element/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Button.cpp.o
.PHONY : src/element/Button.cpp.o

src/element/Button.i: src/element/Button.cpp.i
.PHONY : src/element/Button.i

# target to preprocess a source file
src/element/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Button.cpp.i
.PHONY : src/element/Button.cpp.i

src/element/Button.s: src/element/Button.cpp.s
.PHONY : src/element/Button.s

# target to generate assembly for a file
src/element/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Button.cpp.s
.PHONY : src/element/Button.cpp.s

src/element/Fruit.o: src/element/Fruit.cpp.o
.PHONY : src/element/Fruit.o

# target to build an object file
src/element/Fruit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Fruit.cpp.o
.PHONY : src/element/Fruit.cpp.o

src/element/Fruit.i: src/element/Fruit.cpp.i
.PHONY : src/element/Fruit.i

# target to preprocess a source file
src/element/Fruit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Fruit.cpp.i
.PHONY : src/element/Fruit.cpp.i

src/element/Fruit.s: src/element/Fruit.cpp.s
.PHONY : src/element/Fruit.s

# target to generate assembly for a file
src/element/Fruit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Fruit.cpp.s
.PHONY : src/element/Fruit.cpp.s

src/element/Grid.o: src/element/Grid.cpp.o
.PHONY : src/element/Grid.o

# target to build an object file
src/element/Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Grid.cpp.o
.PHONY : src/element/Grid.cpp.o

src/element/Grid.i: src/element/Grid.cpp.i
.PHONY : src/element/Grid.i

# target to preprocess a source file
src/element/Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Grid.cpp.i
.PHONY : src/element/Grid.cpp.i

src/element/Grid.s: src/element/Grid.cpp.s
.PHONY : src/element/Grid.s

# target to generate assembly for a file
src/element/Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Grid.cpp.s
.PHONY : src/element/Grid.cpp.s

src/element/OptionButton.o: src/element/OptionButton.cpp.o
.PHONY : src/element/OptionButton.o

# target to build an object file
src/element/OptionButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/OptionButton.cpp.o
.PHONY : src/element/OptionButton.cpp.o

src/element/OptionButton.i: src/element/OptionButton.cpp.i
.PHONY : src/element/OptionButton.i

# target to preprocess a source file
src/element/OptionButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/OptionButton.cpp.i
.PHONY : src/element/OptionButton.cpp.i

src/element/OptionButton.s: src/element/OptionButton.cpp.s
.PHONY : src/element/OptionButton.s

# target to generate assembly for a file
src/element/OptionButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/OptionButton.cpp.s
.PHONY : src/element/OptionButton.cpp.s

src/element/Snake.o: src/element/Snake.cpp.o
.PHONY : src/element/Snake.o

# target to build an object file
src/element/Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Snake.cpp.o
.PHONY : src/element/Snake.cpp.o

src/element/Snake.i: src/element/Snake.cpp.i
.PHONY : src/element/Snake.i

# target to preprocess a source file
src/element/Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Snake.cpp.i
.PHONY : src/element/Snake.cpp.i

src/element/Snake.s: src/element/Snake.cpp.s
.PHONY : src/element/Snake.s

# target to generate assembly for a file
src/element/Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/Snake.cpp.s
.PHONY : src/element/Snake.cpp.s

src/element/TitleSprite.o: src/element/TitleSprite.cpp.o
.PHONY : src/element/TitleSprite.o

# target to build an object file
src/element/TitleSprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/TitleSprite.cpp.o
.PHONY : src/element/TitleSprite.cpp.o

src/element/TitleSprite.i: src/element/TitleSprite.cpp.i
.PHONY : src/element/TitleSprite.i

# target to preprocess a source file
src/element/TitleSprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/TitleSprite.cpp.i
.PHONY : src/element/TitleSprite.cpp.i

src/element/TitleSprite.s: src/element/TitleSprite.cpp.s
.PHONY : src/element/TitleSprite.s

# target to generate assembly for a file
src/element/TitleSprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/element/TitleSprite.cpp.s
.PHONY : src/element/TitleSprite.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/screen/AboutScreen.o: src/screen/AboutScreen.cpp.o
.PHONY : src/screen/AboutScreen.o

# target to build an object file
src/screen/AboutScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/AboutScreen.cpp.o
.PHONY : src/screen/AboutScreen.cpp.o

src/screen/AboutScreen.i: src/screen/AboutScreen.cpp.i
.PHONY : src/screen/AboutScreen.i

# target to preprocess a source file
src/screen/AboutScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/AboutScreen.cpp.i
.PHONY : src/screen/AboutScreen.cpp.i

src/screen/AboutScreen.s: src/screen/AboutScreen.cpp.s
.PHONY : src/screen/AboutScreen.s

# target to generate assembly for a file
src/screen/AboutScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/AboutScreen.cpp.s
.PHONY : src/screen/AboutScreen.cpp.s

src/screen/GameOverScreen.o: src/screen/GameOverScreen.cpp.o
.PHONY : src/screen/GameOverScreen.o

# target to build an object file
src/screen/GameOverScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameOverScreen.cpp.o
.PHONY : src/screen/GameOverScreen.cpp.o

src/screen/GameOverScreen.i: src/screen/GameOverScreen.cpp.i
.PHONY : src/screen/GameOverScreen.i

# target to preprocess a source file
src/screen/GameOverScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameOverScreen.cpp.i
.PHONY : src/screen/GameOverScreen.cpp.i

src/screen/GameOverScreen.s: src/screen/GameOverScreen.cpp.s
.PHONY : src/screen/GameOverScreen.s

# target to generate assembly for a file
src/screen/GameOverScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameOverScreen.cpp.s
.PHONY : src/screen/GameOverScreen.cpp.s

src/screen/GameScreen.o: src/screen/GameScreen.cpp.o
.PHONY : src/screen/GameScreen.o

# target to build an object file
src/screen/GameScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameScreen.cpp.o
.PHONY : src/screen/GameScreen.cpp.o

src/screen/GameScreen.i: src/screen/GameScreen.cpp.i
.PHONY : src/screen/GameScreen.i

# target to preprocess a source file
src/screen/GameScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameScreen.cpp.i
.PHONY : src/screen/GameScreen.cpp.i

src/screen/GameScreen.s: src/screen/GameScreen.cpp.s
.PHONY : src/screen/GameScreen.s

# target to generate assembly for a file
src/screen/GameScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/GameScreen.cpp.s
.PHONY : src/screen/GameScreen.cpp.s

src/screen/HelpScreen.o: src/screen/HelpScreen.cpp.o
.PHONY : src/screen/HelpScreen.o

# target to build an object file
src/screen/HelpScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/HelpScreen.cpp.o
.PHONY : src/screen/HelpScreen.cpp.o

src/screen/HelpScreen.i: src/screen/HelpScreen.cpp.i
.PHONY : src/screen/HelpScreen.i

# target to preprocess a source file
src/screen/HelpScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/HelpScreen.cpp.i
.PHONY : src/screen/HelpScreen.cpp.i

src/screen/HelpScreen.s: src/screen/HelpScreen.cpp.s
.PHONY : src/screen/HelpScreen.s

# target to generate assembly for a file
src/screen/HelpScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/HelpScreen.cpp.s
.PHONY : src/screen/HelpScreen.cpp.s

src/screen/MenuScreen.o: src/screen/MenuScreen.cpp.o
.PHONY : src/screen/MenuScreen.o

# target to build an object file
src/screen/MenuScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/MenuScreen.cpp.o
.PHONY : src/screen/MenuScreen.cpp.o

src/screen/MenuScreen.i: src/screen/MenuScreen.cpp.i
.PHONY : src/screen/MenuScreen.i

# target to preprocess a source file
src/screen/MenuScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/MenuScreen.cpp.i
.PHONY : src/screen/MenuScreen.cpp.i

src/screen/MenuScreen.s: src/screen/MenuScreen.cpp.s
.PHONY : src/screen/MenuScreen.s

# target to generate assembly for a file
src/screen/MenuScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/MenuScreen.cpp.s
.PHONY : src/screen/MenuScreen.cpp.s

src/screen/OptionScreen.o: src/screen/OptionScreen.cpp.o
.PHONY : src/screen/OptionScreen.o

# target to build an object file
src/screen/OptionScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/OptionScreen.cpp.o
.PHONY : src/screen/OptionScreen.cpp.o

src/screen/OptionScreen.i: src/screen/OptionScreen.cpp.i
.PHONY : src/screen/OptionScreen.i

# target to preprocess a source file
src/screen/OptionScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/OptionScreen.cpp.i
.PHONY : src/screen/OptionScreen.cpp.i

src/screen/OptionScreen.s: src/screen/OptionScreen.cpp.s
.PHONY : src/screen/OptionScreen.s

# target to generate assembly for a file
src/screen/OptionScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/OptionScreen.cpp.s
.PHONY : src/screen/OptionScreen.cpp.s

src/screen/PauseScreen.o: src/screen/PauseScreen.cpp.o
.PHONY : src/screen/PauseScreen.o

# target to build an object file
src/screen/PauseScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/PauseScreen.cpp.o
.PHONY : src/screen/PauseScreen.cpp.o

src/screen/PauseScreen.i: src/screen/PauseScreen.cpp.i
.PHONY : src/screen/PauseScreen.i

# target to preprocess a source file
src/screen/PauseScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/PauseScreen.cpp.i
.PHONY : src/screen/PauseScreen.cpp.i

src/screen/PauseScreen.s: src/screen/PauseScreen.cpp.s
.PHONY : src/screen/PauseScreen.s

# target to generate assembly for a file
src/screen/PauseScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/PauseScreen.cpp.s
.PHONY : src/screen/PauseScreen.cpp.s

src/screen/Screen.o: src/screen/Screen.cpp.o
.PHONY : src/screen/Screen.o

# target to build an object file
src/screen/Screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/Screen.cpp.o
.PHONY : src/screen/Screen.cpp.o

src/screen/Screen.i: src/screen/Screen.cpp.i
.PHONY : src/screen/Screen.i

# target to preprocess a source file
src/screen/Screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/Screen.cpp.i
.PHONY : src/screen/Screen.cpp.i

src/screen/Screen.s: src/screen/Screen.cpp.s
.PHONY : src/screen/Screen.s

# target to generate assembly for a file
src/screen/Screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/screen/Screen.cpp.s
.PHONY : src/screen/Screen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/element/Button.o"
	@echo "... src/element/Button.i"
	@echo "... src/element/Button.s"
	@echo "... src/element/Fruit.o"
	@echo "... src/element/Fruit.i"
	@echo "... src/element/Fruit.s"
	@echo "... src/element/Grid.o"
	@echo "... src/element/Grid.i"
	@echo "... src/element/Grid.s"
	@echo "... src/element/OptionButton.o"
	@echo "... src/element/OptionButton.i"
	@echo "... src/element/OptionButton.s"
	@echo "... src/element/Snake.o"
	@echo "... src/element/Snake.i"
	@echo "... src/element/Snake.s"
	@echo "... src/element/TitleSprite.o"
	@echo "... src/element/TitleSprite.i"
	@echo "... src/element/TitleSprite.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/screen/AboutScreen.o"
	@echo "... src/screen/AboutScreen.i"
	@echo "... src/screen/AboutScreen.s"
	@echo "... src/screen/GameOverScreen.o"
	@echo "... src/screen/GameOverScreen.i"
	@echo "... src/screen/GameOverScreen.s"
	@echo "... src/screen/GameScreen.o"
	@echo "... src/screen/GameScreen.i"
	@echo "... src/screen/GameScreen.s"
	@echo "... src/screen/HelpScreen.o"
	@echo "... src/screen/HelpScreen.i"
	@echo "... src/screen/HelpScreen.s"
	@echo "... src/screen/MenuScreen.o"
	@echo "... src/screen/MenuScreen.i"
	@echo "... src/screen/MenuScreen.s"
	@echo "... src/screen/OptionScreen.o"
	@echo "... src/screen/OptionScreen.i"
	@echo "... src/screen/OptionScreen.s"
	@echo "... src/screen/PauseScreen.o"
	@echo "... src/screen/PauseScreen.i"
	@echo "... src/screen/PauseScreen.s"
	@echo "... src/screen/Screen.o"
	@echo "... src/screen/Screen.i"
	@echo "... src/screen/Screen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

